# LM vra Specific config

driver:
  name: vra
  username: <%= "#{ENV['KITCHEN_VRA_API_ID'] || ENV['USERNAME']}@lm.lmig.com" %>
  password: <%= require 'json'; ENV['KITCHEN_VRA_API_PASSWORD'] || (JSON.parse(File.read("#{ENV['USERPROFILE']}/.kitchen/vracredentials.json")))['vra_n']  %>
  tenant: vsphere.local
  catalog_id: 49a0c81f-547c-4688-a36b-47bf97ec41f9
  base_url: https://lcp.lmig.com
  verify_ssl: true
  subtenant_id: 20b5ed55-0a79-474f-9bb5-bbfeec53616f
  request_timeout: 30000
  server_ready_retries: 2
  cpus: 1
  memory: 2048
  lease_days: 2

provisioner:
  name: chef_zero
  require_chef_omnibus: false
  sudo: true
  sudo_command: dzdo
  chef_client_path: /opt/chef/bin/chef-client

verifier:
  name: inspec
  sudo: true
  sudo_command: dzdo

transport:
  username: <%= (ENV['KITCHEN_VRA_SSH_ID'] || ENV['USERNAME']).gsub(/n|N/,'a') %>
  password: <%= ENV['KITCHEN_VRA_SSH_PASSWORD'] || 'default' %>

platforms:
  - name: lm_rhel
    driver:
      extra_parameters:
        provider-Machine.SSH:
          type: string
          value: true
        provider-blueprintId:
          type: string
          value: 49a0c81f-547c-4688-a36b-47bf97ec41f9
        provider-LM.SRM:
          type: string
          value: No
        provider-Cafe.Shim.VirtualMachine.MaxCost:
          type: string
          value: 2.2929
        provider-LM.AdditionalSRMInfoLink:
          type: string
          value: https://forge.lmig.com/wiki/pages/viewpage.action?pageId=53399373
        provider-VirtualMachine.Disk1.StorageReservationPolicy:
          type: string
          value: Page
        provider-LM.PlatformType:
          type: string
          value: ICCU
        provider-__reservationPolicyID:
          type: string
          value: 0164F024-9742-49EC-B7EB-6FF92627AC68
        provider-provisioningGroupId:
          type: string
          value: 20B5ED55-0A79-474F-9BB5-BBFEEC53616F
        provider-LM.ProjectName:
          type: string
          value: Chef
        provider-VirtualMachine.Disk0.StorageReservationPolicy:
          type: string
          value: Linux
        provider-Cafe.Shim.VirtualMachine.Description:
          type: string
          value: Test Kitchen
        provider-LM.Chef.Kitchen:
          type: string
          value: true
        provider-LM.Portfolio:
          type: string
          value: Test Kitchen
        provider-LM.NetworkLocation:
          type: string
          value: Internal
        provider-VirtualMachine.Disk2.Label:
          type: string
          value: uservg
        provider-VirtualMachine.Disk0.IsClone:
          type: string
          value: true
        provider-Cafe.Shim.VirtualMachine.NumberOfInstances:
          type: integer
          value: 1
        provider-VirtualMachine.CPU.Count:
          type: integer
          value: 1
        provider-LM.Tier:
          type: string
          value: Other
        provider-LM.MarketVLANSegment:
          type: string
          value: EA
        provider-LM.Domain:
          type: string
          value: <<<LM.LinuxDomain>>>
        provider-VirtualMachine.Memory.Size:
          type: integer
          value: 512
        provider-LM.Environment:
          type: string
          value: Dev
        provider-VirtualMachine.Disk1.Size:
          type: string
          value: 15
        provider-LM.Documentation:
          type: string
          value: https://forge.lmig.com/wiki/display/LCP/Virtual+Machine
        provider-LM.Market:
          type: string
          value: EA
        provider-VirtualMachine.Request.Layout:
          type: string
          value: Layout
        provider-LM.ApplicationName:
          type: string
          value: CHEF - AUTOMATED INFRASTRUCTURE CONFIGURATION MANAGEMENT - 6203C1BF-0B1F-44B0-A165-671255C33480
        provider-LM.ExternalNasMount:
          type: string
          value: False
        provider-VirtualMachine.Disk1.Label:
          type: string
          value: swapvg
        provider-Cafe.Shim.VirtualMachine.AssignToUser:
          type: string
          value: <%= "#{ENV['KITCHEN_VRA_API_ID'] || ENV['USERNAME']}@lm.lmig.com" %>
        provider-LM.MarketBeneficiary:
          type: string
          value: Enterprise
        provider-VirtualMachine.Disk2.StorageReservationPolicy:
          type: string
          value: Appdata
        provider-LM.LinuxDomain:
          type: string
          value: lmig.com
        provider-LM.ApplicationShortName:
          type: string
          value: tstkt
        provider-Cafe.Shim.VirtualMachine.Reason:
          type: string
          value: Test Kitchen
        provider-__Notes:
          type: string
          value: ICCU Test kitchen
        provider-LM.SecureServer:
          type: string
          value: Standard
        provider-VirtualMachine.Disk0.Size:
          type: string
          value: 20
        provider-Cafe.Shim.VirtualMachine.MinCost:
          type: string
          value: 2.2929
        provider-VirtualMachine.Disk2.Size:
          type: string
          value: 20
        provider-LM.ProjectCode:
          type: string
          value: 999986
        provider-LM.PlatformEnvironment:
          type: string
          value: ICCU Internal Nonprod
        provider-LM.provisioningGroupId:
          type: string
          value: 20B5ED55-0A79-474F-9BB5-BBFEEC53616F
        provider-Vrm.DataCenter.Location:
          type: string
          value: PDC
